import pytest
import os
import shutil
import tempfile
from pathlib import Path
from unittest.mock import patch

from aitapes.execution import run_lec_tier1, classify_failure
from aitapes.ledger import wipe_memory, append_entry, _L1_CACHE
from forest_tapes.tapes_core.ast_extractor import ASTExtractor

@pytest.fixture
def temp_repo():
    with tempfile.TemporaryDirectory() as d:
        repo = Path(d)
        (repo / "main.py").write_text("def hello():\n    return 'world'\n", encoding="utf-8")
        yield repo


def test_wipe_memory(temp_repo):
    """Test Feature 11: Amnesiac Retry wipes check/build entries from L1 cache."""
    ledger_path = str(temp_repo / "tapes-ledger.jsonl")
    
    # Pre-populate cache
    append_entry(ledger_path, "plan", "test cmd", "test input", "test output")
    append_entry(ledger_path, "build", "test cmd", "test input", "test output")
    append_entry(ledger_path, "check", "test cmd", "test input", "test output")
    
    assert len(_L1_CACHE[ledger_path]) == 3
    
    wipe_memory(ledger_path)
    
    # Only "plan" should remain
    assert len(_L1_CACHE[ledger_path]) == 1
    assert _L1_CACHE[ledger_path][0].entry_type == "plan"


def test_expansion_ceiling(temp_repo):
    """Test Feature 12: Dynamic Expansion Ceiling copies missing modules."""
    # Create an out-of-scope module
    (temp_repo / "utils.py").write_text("def helper(): return 'tapes'", encoding="utf-8")
    
    # Patch main.py to import the out-of-scope module
    # In a real run, this patch is generated by the LLM
    patches = [
        type("Patch", (), {
            "file": "main.py",
            "target_symbol": "main.hello",
            "search": "return 'world'",
            "replace": "import utils\n    return utils.helper()",
            "reasoning": "mock"
        })()
    ]
    
    # Mock tests asking for hello()
    (temp_repo / "test_main.py").write_text("from main import hello\ndef test_hello():\n    assert hello() == 'tapes'\n", encoding="utf-8")
    
    # Run Tier 1
    res = run_lec_tier1(source_dir=str(temp_repo), patches=patches, test_files=["test_main.py"])
    
    # If expansion works, it should copy utils.py and pass the test.
    # The current execution.py runs tests, catches ModuleNotFoundError, and dynamically copies it into temp_source.
    assert res.passed == True


def test_shattered_host_confirmation(temp_repo):
    """Test Feature 4: Shattered Host Shield prompts before repairing."""
    # Write syntactically invalid file
    (temp_repo / "broken.py").write_text("def broken()  return 1\n", encoding="utf-8")
    
    extractor = ASTExtractor(source_dir=str(temp_repo))
    
    # Mock LLM repair and input confirmation
    def mock_call_llm_json(*args, **kwargs):
        return {"repaired_code": "def broken(): return 1\n"}
    
    with patch("aitapes.llm.call_llm_json", side_effect=mock_call_llm_json), \
         patch("builtins.input", return_value="y") as mock_input:
        
        extractor.index()
        
        mock_input.assert_called_once()
        # Assert file was actually repaired
        assert (temp_repo / "broken.py").read_text(encoding="utf-8") == "def broken(): return 1\n"

