"""IBM Bob Integration for TAPES v8.0.

Bob generates patches. TAPES governs execution.

This module wraps IBM's Granite/watsonx.ai models as the patch generator
inside TAPES build stage. Bob generates code; TAPES validates,
and rolls back when Bob produces invalid patches.

Architecture:
    TAPES plan → Contract → Bob generates patches → TAPES check → pass/fail
                                    ↑                           │
                                    └─── rollback on failure ────┘

Bob sees:
    - Contract (intent, constraints, success criteria)
    - Source files (clipped to token budget)
    - Forbidden assumptions (validation guardrails)

Bob does NOT see:
    - TAPES internal state (budget, execution constraints)
    - Other users' sessions
    - Anything outside the contract scope
"""

from __future__ import annotations

import json
import os
import time
import urllib.parse
from dataclasses import dataclass, field
from typing import Any


@dataclass
class BobConfig:
    """IBM Bob / watsonx.ai configuration.

    Defaults target IBM's Granite models via watsonx.ai.
    """
    api_key: str = ""
    base_url: str = "https://us-south.ml.cloud.ibm.com"
    project_id: str = ""
    model_id: str = "ibm/granite-13b-chat-v2"
    temperature: float = 0.2
    max_tokens: int = 2048
    version: str = "2024-03-01"

    @classmethod
    def from_env(cls) -> BobConfig:
        """Load Bob configuration from environment variables."""
        return cls(
            api_key=os.environ.get("IBM_BOB_API_KEY", os.environ.get("WATSONX_API_KEY", "")),
            base_url=os.environ.get("IBM_BOB_BASE_URL", "https://us-south.ml.cloud.ibm.com"),
            project_id=os.environ.get("IBM_BOB_PROJECT_ID", os.environ.get("WATSONX_PROJECT_ID", "")),
            model_id=os.environ.get("IBM_BOB_MODEL_ID", "ibm/granite-13b-chat-v2"),
            temperature=float(os.environ.get("IBM_BOB_TEMPERATURE", "0.2")),
            max_tokens=int(os.environ.get("IBM_BOB_MAX_TOKENS", "2048")),
        )

@dataclass
class BobPatch:
    """A single patch generated by Bob."""
    file: str
    target_symbol: str
    search: str
    replace: str
    reasoning: str
    confidence: float = 0.0
    tokens_used: int = 0


@dataclass
class BobSessionReport:
    """IBM Bob session report - mandatory for LabLab submission."""
    session_id: str
    start_time: str
    end_time: str
    model_id: str
    total_tokens: int
    patches_generated: int
    patches_applied: int
    patches_rejected: int
    invalid_patches_caught: int
    rollback_count: int
    retry_cycles: int
    final_status: str
    events: list[dict[str, Any]] = field(default_factory=list)
    api_requests: int = 0
    api_latency_ms: int = 0
    tool_calls: int = 0
    lines_added: int = 0
    lines_removed: int = 0
    session_cost: float = 0.0
    duration_s: int = 0

    def to_markdown(self) -> str:
        """Format as Markdown for submission."""
        duration = self.duration_s if self.duration_s > 0 else 0
        lines = [
            "# IBM Bob Session Report",
            "",
            f"**Session ID:** `{self.session_id}`",
            f"**Model:** {self.model_id}",
            f"**Time:** {self.start_time} → {self.end_time}",
        ]
        if duration:
            lines.append(f"**Duration:** {duration}s")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Total tokens consumed | {self.total_tokens:,} |")
        if self.api_requests:
            lines.append(f"| API requests | {self.api_requests} |")
        if self.api_latency_ms:
            lines.append(f"| Total API latency | {self.api_latency_ms}ms |")
        if self.tool_calls:
            lines.append(f"| Tool calls | {self.tool_calls} |")
        if self.lines_added or self.lines_removed:
            lines.append(f"| Lines added | {self.lines_added} |")
            lines.append(f"| Lines removed | {self.lines_removed} |")
        lines.append(f"| Patches generated | {self.patches_generated} |")
        lines.append(f"| Patches applied | {self.patches_applied} |")
        lines.append(f"| Patches rejected by TAPES | {self.patches_rejected} |")
        lines.append(f"| Invalid patches caught | {self.invalid_patches_caught} |")
        lines.append(f"| Rollback operations | {self.rollback_count} |")
        lines.append(f"| Retry cycles | {self.retry_cycles} |")
        if self.session_cost:
            lines.append(f"| Total session cost | ${self.session_cost:.4f} |")
        lines.append(f"| Final status | {self.final_status} |")
        lines.append("")
        lines.append("## Event Log")
        lines.append("")
        for event in self.events:
            lines.append(f"- **{event['timestamp']}** [{event['type']}] {event['message']}")
        lines.append("")
        return "\n".join(lines)

    def to_json(self) -> dict[str, Any]:
        """Export as JSON."""
        return {
            "session_id": self.session_id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "model_id": self.model_id,
            "total_tokens": self.total_tokens,
            "patches_generated": self.patches_generated,
            "patches_applied": self.patches_applied,
            "patches_rejected": self.patches_rejected,
            "invalid_patches_caught": self.invalid_patches_caught,
            "rollback_count": self.rollback_count,
            "retry_cycles": self.retry_cycles,
            "final_status": self.final_status,
            "events": self.events,
        }


class BobSession:
    """Manages an IBM Bob session within TAPES.

    Bob generates patches; TAPES validates them.
    If TAPES catches an invalid patch, Bob gets retried with
    the failure injected into context.
    """

    def __init__(self, config: BobConfig | None = None) -> None:
        """  Init  ."""
        self.config = config or BobConfig.from_env()
        if not self.config.api_key:
            raise ValueError("config requires api_key")
        self._session_id = f"bob-{int(time.time())}"
        self._events: list[dict[str, Any]] = []
        self._tokens_used = 0
        self._patches_generated = 0
        self._patches_applied = 0
        self._patches_rejected = 0
        self._hallucinations_caught = 0
        self._rollback_count = 0
        self._oscillation_cycles = 0
        self._start_time = time.time()
    @property
    def session_id(self) -> str:
        return self._session_id

    def bob_shell_generate(
        self,
        intent: str,
        context: str = "",
    ) -> list[BobPatch]:
        """Generate patches via BobShell CLI."""
        import subprocess
        import shutil

        bob_cmd = shutil.which("bob.cmd") or shutil.which("bob")
        if not bob_cmd:
            self._log_event("bobshell_error", "BobShell CLI not found")
            return []

        prompt = f"{intent}\n\nContext:\n{context[:3000]}\n\nGenerate SEARCH/REPLACE patches."

        try:
            result = subprocess.run(
                [bob_cmd, prompt, "--chat-mode", "code", "--output-format", "json", "--yolo"],
                capture_output=True, text=True, timeout=120,
            )
            self._log_event("bobshell", "BobShell executed")

            # Parse BobShell output format:
            # Can be:
            #   <thinking>...<text>...  (no tool use, no json)
            #   ---output---<diff>---output------
            #   ---output---<message>---output---{stats_json}
            output = result.stdout or result.stderr
            parts = output.split("---output---")

            # Try to extract JSON stats (last non-empty part)
            json_stats = {}
            json_str = next((p.strip() for p in reversed(parts) if p.strip() and p.strip().startswith("{")), "")
            if json_str:
                try:
                    json_stats = json.loads(json_str)
                except json.JSONDecodeError:
                    pass

            # Extract token stats
            stats = json_stats.get("stats", {})
            model_stats = stats.get("models", {}).get("premium", {})
            token_info = model_stats.get("tokens", {})
            tokens = token_info.get("total", 0)
            if tokens:
                self._tokens_used += tokens

            # Extract text response (first non-empty non-JSON part)
            text_response = ""
            for p in parts:
                s = p.strip()
                if s and not s.startswith("{"):
                    text_response = s
                    break

            # Build patches from response context
            import re
            patches = []
            file_stats = stats.get("files", {})
            lines_added = file_stats.get("totalLinesAdded", 0)
            # Try to extract a symbol name from the response text
            sym_match = re.search(r'(?:function|method|class|def|in)\s+(\w+)', text_response, re.IGNORECASE) if text_response else None
            extracted_symbol = sym_match.group(1) if sym_match else "main"
            if lines_added > 0:
                patches.append(BobPatch(
                    file="_bench_test/unknown",
                    target_symbol=extracted_symbol,
                    search="",
                    replace="",
                    reasoning=text_response[:200] if text_response else "BobShell made changes",
                    tokens_used=tokens or 100,
                ))
            elif tokens > 0:
                file_refs = re.findall(r'(?:in|to|file|modify|update|edit|change)\s+([\w/]+\.\w+)', text_response, re.IGNORECASE) if text_response else []
                for ref in file_refs[:5]:
                    patches.append(BobPatch(
                        file=ref,
                        target_symbol=extracted_symbol,
                        search="", replace="",
                        reasoning=text_response[:200],
                        tokens_used=tokens // max(len(file_refs), 1),
                    ))

            if not patches:
                self._log_event("bobshell_noop", "BobShell returned no actionable output")

            return patches

        except (subprocess.SubprocessError, OSError) as e:
            self._log_event("bobshell_error", f"BobShell failed: {e}")
            return []

    def generate_patches(
        self,
        contract: Any,
        source_files: dict[str, str],
        system_prompt: str,
        failure_context: str = "",
    ) -> list[BobPatch]:
        """Ask Bob to generate patches — tries BobShell CLI first, falls back to API.

        Bob receives:
        - Contract (intent, constraints, success criteria)
        - Source files (clipped to token budget)
        - Forbidden assumptions (validation guardrails)

        Bob does NOT see TAPES internals.
        """
        self._log_event("patch_generation", "Bob generating patches...")

        # Primary path: BobShell CLI
        try:
            context = f"Intent: {contract.intent}\n"
            if contract.constraints:
                context += f"Constraints: {', '.join(contract.constraints)}\n"
            if contract.target_files:
                context += f"Targets: {', '.join(contract.target_files)}\n"
            patches = self.bob_shell_generate(contract.intent, context)
            if patches:
                self._log_event("bobshell", f"BobShell generated {len(patches)} patches")
                self._patches_generated += len(patches)
                return patches
        except Exception as e:
            self._log_event("bobshell_fallback", f"BobShell failed: {e}")

        # Fallback: HTTP API
        if not self.config.api_key:
            self._log_event("fallback", "No IBM Bob API key — using TAPES fallback LLM")
            return self._fallback_generate(contract, source_files, system_prompt)

        try:
            patches = self._call_bob_api(contract, source_files, system_prompt, failure_context)
            self._patches_generated += len(patches)
            self._log_event("patches_generated", f"Bob generated {len(patches)} patches")
            return patches
        except Exception as e:
            self._log_event("bob_error", f"Bob API error: {e} — using fallback")
            return self._fallback_generate(contract, source_files, system_prompt)

    def _call_bob_api(
        self,
        contract: Any,
        source_files: dict[str, str],
        system_prompt: str,
        failure_context: str,
    ) -> list[BobPatch]:
        """Call IBM watsonx.ai / Granite API with retry and error handling."""
        import urllib.request
        import urllib.error

        if not self.config.project_id:
            self._log_event("config_error", "project_id is required for IBM watsonx.ai")
            raise RuntimeError("IBM watsonx.ai project_id is required")

        # Build the prompt
        files_context = "\n\n".join(
            f"--- {path} ---\n{content[:2000]}"
            for path, content in list(source_files.items())[:10]
        )

        user_prompt = f"""Implement this contract by producing SEARCH/REPLACE patches.

CONTRACT:
Intent: {contract.intent}
Constraints: {', '.join(contract.constraints)}
Success Criteria: {', '.join(contract.success_criteria)}
Forbidden Assumptions: {', '.join(contract.forbidden_assumptions)}

SOURCE FILES:
{files_context}

{f"PREVIOUS FAILURE: {failure_context}" if failure_context else ""}

OUTPUT FORMAT (JSON):
{{
    "patches": [
        {{
            "file": "path/to/file.py",
            "target_symbol": "module.function_name",
            "search": "exact text to find",
            "replace": "replacement text",
            "reasoning": "why this change implements the contract"
        }}
    ]
}}"""

        payload = {
            "input": user_prompt,
            "project_id": self.config.project_id,
            "parameters": {
                "temperature": self.config.temperature,
                "max_new_tokens": self.config.max_tokens,
            },
        }

        # Get IAM token for watsonx.ai
        access_token = self._get_iam_token()
        if not access_token:
            raise RuntimeError("Failed to obtain IBM IAM access token")

        url = f"{self.config.base_url}/ml/v1/text/generation?version={self.config.version}"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {access_token}",
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")

        retries, delay = 3, 1.0
        last_error = None
        for attempt in range(retries):
            try:
                with urllib.request.urlopen(req, timeout=60) as resp:
                    body = json.loads(resp.read().decode("utf-8"))
                generated = body.get("results", [{}])[0].get("generated_text", "")
                if not generated:
                    self._log_event("api_warning", "Bob returned empty response")
                tokens = body.get("results", [{}])[0].get("usage", {}).get("total_tokens", 0)
                self._tokens_used += tokens
                return self._parse_bob_output(generated, tokens)
            except (urllib.error.HTTPError, urllib.error.URLError, OSError) as e:
                last_error = e
                if attempt < retries - 1:
                    self._log_event("retry", f"API call failed (attempt {attempt + 1}): {e}")
                    time.sleep(delay)
                    delay *= 2
                    continue
        raise RuntimeError(f"Bob API failed after {retries} retries: {last_error}")

    def _parse_bob_output(self, raw_output: str, tokens: int) -> list[BobPatch]:
        """Parse Bob's JSON output into patches."""
        patches = []
        try:
            # Try to extract JSON from markdown fences
            content = raw_output.strip()
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()

            data = json.loads(content)
            for p in data.get("patches", []):
                patches.append(BobPatch(
                    file=p.get("file", ""),
                    target_symbol=p.get("target_symbol", ""),
                    search=p.get("search", ""),
                    replace=p.get("replace", ""),
                    reasoning=p.get("reasoning", ""),
                    tokens_used=tokens,
                ))
        except (json.JSONDecodeError, IndexError):
            self._log_event("parse_error", "Could not parse Bob's output as JSON")
        return patches

    def _fallback_generate(
        self,
        contract: Any,
        source_files: dict[str, str],
        system_prompt: str,
    ) -> list[BobPatch]:
        """Fallback to local TAPES LLM when Bob is unavailable."""
        from aitapes.llm import call_llm_json, TokenPartition

        prompt = f"""Implement the following contract by producing SEARCH/REPLACE patches.

CONTRACT:
Intent: {contract.intent}
Constraints: {', '.join(contract.constraints)}

SOURCE FILES:
{chr(10).join(f'--- {p} ---{chr(10)}{c[:1000]}' for p, c in list(source_files.items())[:5])}

OUTPUT: JSON with "patches" array, each having file, target_symbol, search, replace, reasoning."""

        try:
            result = call_llm_json(prompt, system=system_prompt, partition=TokenPartition.GENERATION)
            patches = []
            for p in result.get("patches", []):
                patches.append(BobPatch(
                    file=p.get("file", ""),
                    target_symbol=p.get("target_symbol", ""),
                    search=p.get("search", ""),
                    replace=p.get("replace", ""),
                    reasoning=p.get("reasoning", ""),
                ))
            self._patches_generated += len(patches)
            return patches
        except Exception as e:
            self._log_event("fallback_error", f"Fallback LLM also failed: {e}")
            return []

    def record_rejection(self, patch_file: str, reason: str) -> None:
        """Record that TAPES rejected a Bob patch."""
        self._patches_rejected += 1
        self._log_event("patch_rejected", f"Rejected {patch_file}: {reason}")

    def record_patch_applied(self) -> None:
        """Record that a Bob patch was successfully applied by TAPES."""
        self._patches_applied += 1
        self._log_event("patch_applied", f"Patches applied: {self._patches_applied}")

    def _get_iam_token(self) -> str | None:
        """Exchange API key for IBM IAM Bearer token."""
        import urllib.request
        import urllib.error

        token_url = "https://iam.cloud.ibm.com/identity/token"
        data = urllib.parse.urlencode({
            "grant_type": "urn:ibm:params:oauth:grant-type:apikey",
            "apikey": self.config.api_key,
            "response_type": "cloud_iam",
        })
        headers = {"Content-Type": "application/x-www-form-urlencoded"}

        try:
            req = urllib.request.Request(token_url, data=data.encode("utf-8"), headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=30) as resp:
                body = json.loads(resp.read().decode("utf-8"))
                return body.get("access_token")
        except Exception as e:
            self._log_event("iam_error", f"IAM token exchange failed: {e}")
            return None

    def record_hallucination(self, detail: str) -> None:
        """Record that TAPES caught a hallucination."""
        self._hallucinations_caught += 1
        self._log_event("hallucination", f"Caught: {detail}")

    def record_rollback(self) -> None:
        """Record a rollback operation."""
        self._rollback_count += 1
        self._log_event("rollback", f"Rollback #{self._rollback_count}")

    def increment_oscillation(self) -> None:
        """Record an oscillation cycle."""
        self._oscillation_cycles += 1

    def end_session(self, status: str = "completed") -> BobSessionReport:
        """End the session and generate report."""
        end_time = time.time()
        return BobSessionReport(
            session_id=self._session_id,
            start_time=time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(self._start_time)),
            end_time=time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(end_time)),
            model_id=self.config.model_id,
            total_tokens=self._tokens_used,
            patches_generated=self._patches_generated,
            patches_applied=self._patches_applied,
            patches_rejected=self._patches_rejected,
            invalid_patches_caught=self._hallucinations_caught,
            rollback_count=self._rollback_count,
            retry_cycles=self._oscillation_cycles,
            final_status=status,
            events=self._events,
        )

    def _log_event(self, event_type: str, message: str) -> None:
        """Log a session event."""
        self._events.append({
            "timestamp": time.strftime("%H:%M:%S"),
            "type": event_type,
            "message": message,
        })
