"""Generate Bob session report with real bouncer intercepts.

Combines:
  1. Historical BobShell session data (3 tasks, 67k tokens, $0.17)
  2. Live TAPES kill-shot: bouncer intercepts a protected file patch

The intercept is REAL — runs the actual offline builder + bouncer pipeline.
"""

import os, sys, time, json, shutil, subprocess, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(str(ROOT))

from aitapes.bob import BobSessionReport
from aitapes.offline_builder import generate_patches
from aitapes.bouncer import check_all, PROTECTED_FILES, MAX_MUTATION_FILES

# ═══════════════════════════════════════════════════════════════════════════════
#  PART 1: Live bouncer intercept demonstration
# ═══════════════════════════════════════════════════════════════════════════════

with tempfile.TemporaryDirectory() as tmpdir:
    # Create a minimal test project with a protected file
    project = Path(tmpdir) / "demo_project"
    project.mkdir()
    (project / "legacy_auth.py").write_text(
        "import hashlib\n"
        "\n"
        "def authenticate(username, password):\n"
        '    """Authenticate user."""\n'
        '    return {"id": 1}\n'
        "\n"
        "def get_user_role(user_id):\n"
        "    return \"admin\"\n"
    )

    # Intent that triggers patches across multiple files including legacy_auth.py
    intent = "add validation to authenticate"
    print(f"  Generating patches for: {intent}")
    output = generate_patches(str(project), intent)
    patches = list(output.patches)
    print(f"  Generated {len(patches)} patches")

    # Run bouncer — it intercepts legacy_auth.py patches
    approved, remediations = check_all(patches, str(project))
    redirects = [r for r in remediations if r.action == "redirect"]
    rejects = [r for r in remediations if r.action == "reject"]

    print(f"  Bouncer: {len(redirects)} redirects, {len(rejects)} rejects")
    for r in redirects:
        print(f"    -> {r.original_file} redirected to {r.redirect_target}")
    for r in rejects:
        print(f"    -> {r.original_file} rejected: {r.reason}")
    print(f"  Approved: {len(approved)} patches for {len({p.file for p in approved})} files")

    # ═══════════════════════════════════════════════════════════════════════════
    #  PART 2: Combine with BobShell data + build report
    # ═══════════════════════════════════════════════════════════════════════════

    start_time = time.time()

    events = [
        {"timestamp": "12:20:48", "type": "session_start",
         "message": "BobShell session started"},
        {"timestamp": "12:20:48", "type": "task_complete",
         "message": "Task 'Add a type hint to audit_logger.py': 22,617 tokens, $0.0565, 19s"},
        {"timestamp": "12:21:07", "type": "task_complete",
         "message": "Task 'Add input validation to auth_routes.py login': 23,675 tokens, $0.0592, 32s"},
        {"timestamp": "12:21:39", "type": "task_complete",
         "message": "Task 'Add a docstring to config.py': 21,641 tokens, $0.0541, 16s"},
    ]

    # Add bouncer intercept events from the real run
    for r in redirects:
        events.append({
            "timestamp": time.strftime("%H:%M:%S", time.localtime(time.time())),
            "type": "bouncer_intercept",
            "message": f"BOUNCER INTERCEPT: {r.original_file} -> {r.redirect_target}. {r.reason}",
        })
    for r in rejects:
        events.append({
            "timestamp": time.strftime("%H:%M:%S", time.localtime(time.time())),
            "type": "bouncer_reject",
            "message": f"BOUNCER REJECTED: {r.original_file}. {r.reason}",
        })

    events.append({
        "timestamp": time.strftime("%H:%M:%S", time.localtime(time.time())),
        "type": "session_end",
        "message": f"Session complete: 3 BobShell tasks + 1 TAPES governance pass",
    })

    report = BobSessionReport(
        session_id="bob-1778914248",
        start_time="2026-05-16T12:20:48",
        end_time=time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(time.time())),
        model_id="ibm/granite-13b-chat-v2 (via BobShell premium)",
        total_tokens=67933,
        patches_generated=6 + len(patches),
        patches_applied=0,
        patches_rejected=len(rejects),
        invalid_patches_caught=0,
        rollback_count=0,
        retry_cycles=0,
        final_status="completed",
        events=events,
        api_requests=6,
        api_latency_ms=43826,
        tool_calls=6,
        lines_added=0,
        lines_removed=0,
        session_cost=0.1698,
        duration_s=67,
    )

    out_path = ROOT / "bob-session-report.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(report.to_markdown())

    print(f"\n{'='*50}")
    print(f"Session report: {out_path}")
    print(f"Patches generated by BobShell: 6")
    print(f"Patches generated by TAPES pass: {len(patches)}")
    print(f"Bouncer redirects: {len(redirects)}")
    print(f"Bouncer rejects: {len(rejects)}")
    print(f"Approved after governance: {len(approved)}")
    print(f"{'='*50}")

    # Show the redirect/reject entries in the report
    print("\nGovernance events recorded in report:")
    for e in events:
        if e["type"] in ("bouncer_intercept", "bouncer_reject"):
            print(f"  [{e['timestamp']}] {e['message']}")
